NotasLocal/config/routes.rb
Rails.application.routes.draw do
  resources :collection_notes
  resources :collections
  get 'friends/index'
  get 'friends/destroy'
  resources :friend_requests
get "logout" => "session#destroy", :as => "logout"
get "login" => "session#new", :as => "login"
post "login" => "session#create"
get "signup" => "users#new", :as => "signup"
resources :users
resources :session
resources :notes
resources :friends
resources :friend_requests
root :to => "session#new"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

NotasLocal/app/models/collection.rb
class Collection < ApplicationRecord
  belongs_to :user
end

NotasLocal/app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :set_collection, only: [:show, :edit, :update, :destroy]

# GET /collections
  # GET /collections.json
  def index
    if(session[:admin] == true)
      @collections = Collection.all
    else
      @collections = Collection.where(:user_id => [session[:user],"0"])
    end
  end


def create
    @collection = Collection.new(collection_params)

    respond_to do |format|
      if @collection.save
        format.html { redirect_to @collection, notice: 'Collection was successfully created.' }
        format.json { render :show, status: :created, location: @collection }
      else
        format.html { render :new }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  
  # GET /collections/new
  def new
    @collection = Collection.new
  end

  # GET /collections/1/edit
  def edit
  end

  # POST /collections
  # POST /collections.json
  

  # PATCH/PUT /collections/1
  # PATCH/PUT /collections/1.json
  def update
    respond_to do |format|
      if @collection.update(collection_params)
        format.html { redirect_to @collection, notice: 'Collection was successfully updated.' }
        format.json { render :show, status: :ok, location: @collection }
      else
        format.html { render :edit }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collections/1
  # DELETE /collections/1.json
  def destroy
    if @collection.user_id = session[:user] || (session[:admin] == true)
      @collection.destroy
      respond_to do |format|
        format.html { redirect_to collections_url, notice: 'Collection was successfully destroyed.' }
        format.json { head :no_content }
        end
    else
      respond_to do |format|
        format.html { redirect_to collections_url, alert: 'You cannot delete another user’s collection!' }
        format.json { head :no_content }
      end
    end  
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collection
      @collection = Collection.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def collection_params
      params.require(:collection).permit(:name, :user_id)
    end
end

NotasLocal/app/helpers/collections_helper.rb
module CollectionsHelper
end

NotasLocal/app/views/collections/_form.html.erb
<%= form_for(@collection) do |form| %>
  <% if collection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(collection.errors.count, "error") %> prohibited this collection from being saved:</h2>

      <ul>
      <% collection.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :user_id, :hidden => true %>&nbsp;
    <%= form.text_field :user_id, :value => session[:user], :hidden => true, :readonly => true%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

NotasLocal/app/views/collections/edit.html.erb
<h1>Editing Collection</h1>

<%= render 'form', collection: @collection %>

<%= link_to 'Show', @collection %> |
<%= link_to 'Back', collections_path %>

NotasLocal/app/views/collections/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Collections</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @collections.each do |collection| %>
      <tr>
        <td><%= collection.name %></td>
        <td><%= collection.user.name %></td>
        <td><%= link_to 'Show', collection %></td>
        <td><%= link_to 'Edit', edit_collection_path(collection) %></td>
        <td><%= link_to 'Destroy', collection, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Collection', new_collection_path %>

NotasLocal/app/views/collections/new.html.erb
<h1>New Collection</h1>

<%= render 'form', collection: @collection %>

<%= link_to 'Back', collections_path %>

NotasLocal/app/views/collections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @collection.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @collection.user.name %>
</p>

<%= link_to 'Edit', edit_collection_path(@collection) %> |
<%= link_to 'Back', collections_path %>