NotasLocal/config/routes.rb
Rails.application.routes.draw do
  resources :collection_notes
  resources :collections
  get 'friends/index'
  get 'friends/destroy'
  resources :friend_requests
get "logout" => "session#destroy", :as => "logout"
get "login" => "session#new", :as => "login"
post "login" => "session#create"
get "signup" => "users#new", :as => "signup"
resources :users
resources :session
resources :notes
resources :friends
resources :friend_requests
root :to => "session#new"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

NotasLocal/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
 <title>NotesT5</title>
 <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
 <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
 <%= csrf_meta_tags %>
</head>
<body style="background-image: url('../../bg.jpg'); background-size: cover;">
 <div id="container" class="container-fluid">
 	<div class="row">
 		<div class="col-md-12">
 			<div class="user_nav">
				 <% if session[:user] %>
 				Logged in as <%= session[:username] %>.
 				<%= link_to "Log out", logout_path %>
 				<% else %>
 				<%= link_to "Sign up", signup_path %> or
 				<%= link_to "log in", login_path %>.
 				<% end %>
 			</div>
 		</div>
 	</div>
 	<% if session[:user] %>
 	<div class="row">
 		<div class="col-md-12">
 			<div class="user_nav">
 				<%= link_to 'Notes',notes_path, :class=>"btn btn-info" %>
 				<%= link_to 'See friends',friends_path, :class=>"btn btn-info" %>
 				<%= link_to 'New friends',friend_requests_path, :class=>"btn btn-info" %>
 				<%= link_to 'Collections',collections_path, :class=>"btn btn-info" %>
 			</div>
 		</div>
 	</div>
 	<% end %>
 	<% if session[:admin]==true %>
 	<div class="row">
 		<div class="col-md-3 col-md-offset-7">
 			<div class="user_nav">
 					<%= link_to 'Users',users_path, :class=>"btn btn-danger" %>
 			</div>
 		</div>
 	</div>
 	<% end %>
 		<% flash.each do |name, msg| %>
 		<%= content_tag :div, msg, :id => "flash_#{name}" %>
 		<% end %>
 		<%= yield %>
 </div>
</body>
</html>