NotasLocal/config/routes.rb
Rails.application.routes.draw do
  resources :collection_notes
  resources :collections
  get 'friends/index'
  get 'friends/destroy'
  resources :friend_requests
get "logout" => "session#destroy", :as => "logout"
get "login" => "session#new", :as => "login"
post "login" => "session#create"
get "signup" => "users#new", :as => "signup"
resources :users
resources :session
resources :notes
resources :friends
resources :friend_requests
root :to => "session#new"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

NotasLocal/app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user
  mount_uploader :image, ImageUploader
end

NotasLocal/app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :authenticate!
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  # GET /notes
  # GET /notes.json
  def index
    if(session[:admin] == true)
      @notes = Note.all
    else
      @notes = Note.where(:user_id => [session[:user],"0"])
    end
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
      @note = Note.new
  end

  # GET /notes/1/edit
  def edit
    if @note.user.id = session[:user] || (session[:admin] == true)
      @note = Note.find(params[:id])
    else
      redirect_to notes_path, :alert => "You cannot edit another user’s note!"
      
    end
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)
    @note.user = User.find_by name: session[:username] 

    respond_to do |format|
      if @note.save
        format.html { redirect_to notes_url, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to notes_url, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy

  	if @note.user.id = session[:user] || (session[:admin] == true)
      @note.destroy
      respond_to do |format|
        format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
        format.json { head :no_content }
        end
    else
      respond_to do |format|
        format.html { redirect_to notes_url, alert: 'You cannot delete another user’s note!' }
        format.json { head :no_content }
      
      end
    end  
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:title, :text, :image, :user_id)
    end
end

NotasLocal/app/helpers/notes_helper.rb
module NotesHelper
end

NotasLocal/app/views/notes/_form.html.erb
<div class="row">
  <div class="col-md-1">&nbsp;
  </div>
  <div class="col-md-7" style="background-image: url('../../postit.png'); background-repeat: no-repeat;">

<%= form_for(@note) do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% @note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<br><br><br>

<table>
  <tr><td>&nbsp;&nbsp;</td>
  <td colspan="2">
    <div class="field">
      <%= f.label :user_id %>&nbsp;
      <%= f.label :user_id, :value => session[:username], :readonly => true,:style =>"background: transparent"%>
    </div>

    <div class ="field" >
      <%= f.label :title %>&nbsp;
      <%= f.text_field :title, :style =>"background: transparent" %>
    </div>

    <div class="field" >
     <%= f.label :text %><br>
     <%= f.text_area :text, :style =>"background: transparent", :cols=>"37", :rows=>"4" %>
    </div>
  
    <div class="field">
      <%= f.label :image %><br>
    </div>
      <div class="field">
        <%= f.file_field :image %><br>
      &nbsp;&nbsp;
    </div>
  
  </td></tr>
  <tr><td></td><td></td><td align="right">
  
  <div class="actions">
    <%= f.submit :class=>"btn btn-success" %>
    <br><br><br>
  </div>
</td></tr></table>
<% end %>
</div>
</div>

NotasLocal/app/views/notes/edit.html.erb
<h1 class="text-primary">Editing Note</h1>

<%= render 'form' %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

NotasLocal/app/views/notes/index.html.erb
<div class="row">
  <div class="col-md-12">
    <p id="notice"><%= notice %></p>
    <h1 class="text-primary">Listing Notes</h1>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <table align="center"><tr><td align="center">
    <%= link_to 'New Note', new_note_path, :class=>"btn btn-success" %>
    <%= link_to 'New Collection', new_collection_path, :class=>"btn btn-success" %>
  </td></tr></table>
  </div>
</div>
<div class="row">

  <% @notes.each do |note| %>
    <div class="col-md-3 ">
      <table style="background-image: url('../../postit2.png'); background-repeat: no-repeat;">
          <tr><td colspan="3" align="center"><br><br>
            <%= note.title %><br>
            <textarea style ="background: transparent" cols="15" rows="3"><%= note.text %></textarea>
          </td></tr>

          <tr>
            <td colspan="3" align="center"><%= note.user.name %><br>
              <% if note.image.thumb.url %>
                <%= image_tag note.image.thumb.url %>
              <% end %>
              <br><br><br>
            </td>
          </tr>
          <tr>
            <td><%= link_to 'Show', note, :class=>"btn btn-success" %></td>
            <td><%= link_to 'Edit', edit_note_path(note), :class=>"btn btn-warning" %></td>
            <td><%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"btn btn-danger" %></td>
          </tr>
      </table>
    </div>
  <% end %>
</div>

<div class="row">
  <div class="col-md-12" ><br>
    <table align="center"><tr><td align="center">
    <%= link_to 'New Note', new_note_path, :class=>"btn btn-success" %>
    <%= link_to 'New Collection', new_collection_path, :class=>"btn btn-success" %>
  </td></tr></table>
  </div>
</div>

NotasLocal/app/views/notes/new.html.erb
<h1 class="text-primary">New Note</h1>

<%= render 'form' %>

<%= link_to 'Back', notes_path %>

NotasLocal/app/views/notes/show.html.erb
<div class="row">
  <div class="col-md-12">
	<p id="notice"><%= notice %></p>
   </div>
</div>

<div class="row">
  <div class="col-md-1">&nbsp;
  </div>
  <div class="col-md-7" style="background-image: url('../../postit.png'); background-repeat: no-repeat;">
<br><br><br>

<table>
  <tr><td>&nbsp;&nbsp;</td>
  	<td>
    <p><strong>&nbsp;Title:</strong><%= @note.title %></p>
  	<p><strong>User:</strong><%= @note.user.name %></p>
	<p><strong>Text:</strong></p>
		<textarea style ="background: transparent" cols="37" rows="4"><%= @note.text %></textarea>
	<p><strong>&nbsp;&nbsp;Image:</strong>
    <% if @note.image.thumb.url %>
        <%= image_tag @note.image.thumb.url %>
    <% end %>
  </p>
	<br><br><br><br>
	</td>
  </tr>
</table>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
	<%= link_to 'Edit', edit_note_path(@note) %> |
	<%= link_to 'Back', notes_path %>
  </div>
</div>